#!/bin/bash

VALID_INPUT=(
	'data/miRNAs-test.fa data/subject/premiRNA.fa data/extend-alignment.3p.txt'
	'data/miRNAs-test.fa data/subject/premiRNA.fa data/extend-alignment.5p.txt'
)

CORRECT_OUTPUT=(
	'correct/extend-alignment.3p.txt'
	'correct/extend-alignment.5p.txt'
)

FOUT=(
	'results/extend-alignment.3p.txt'
	'results/extend-alignment.5p.txt'
)

test_function() {
	local IN="$1"
	local OUT="$2"
	mkdir -p "$(dirname ${OUT})"
	bin/extend-alignment  ${IN} > "$OUT"

}

test_valid() {
	rv=0
	for i in `seq 0 $(( ${#VALID_INPUT[@]} - 1 ))`; do
		test_function "${VALID_INPUT[$i]}" "${FOUT[$i]}"
		diff "${CORRECT_OUTPUT[$i]}" "${FOUT[$i]}" \
		|| rv=1
	done
	exit "$rv"
}

test_valid >&2
