#!/bin/bash

VALID_INPUT=(
	'data/format-report.txt'
)

CORRECT_OUTPUT=(
	'correct/format-report.txt'
)

FOUT=(
	'results/format-report.txt'
)

test_function() {
	local IN="$1"
	local OUT="$2"
	mkdir -p "$(dirname ${OUT})"
	format-report "$IN" > "$OUT"

}

test_valid() {
	rv=0
	for i in `seq 0 $(( ${#VALID_INPUT[@]} - 1 ))`; do
		test_function "${VALID_INPUT[$i]}" "${FOUT[$i]}"
		diff "${CORRECT_OUTPUT[$i]}" "${FOUT[$i]}" \
		|| rv=1
	done
	exit "$rv"
}

test_valid >&2
