< config.mk

results/%.pre-mat.blastn.txt:	data/%.fa
	set -x
	mkdir -p "$(dirname "${target}")"
	blastn \
		-query "${prereq}" \
		-db "${REFERENCE}" \
		-task blastn \
		-reward 1 \
		-penalty -1 \
		-gapopen 2 \
		-gapextend 2 \
		-word_size 7 \
		-dust no \
		-soft_masking false \
		-max_target_seqs 100 \
		-num_threads "${NT}" \
		-evalue 10 \
		-outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore sstrand" \
	| bin/add-header \
		> "${target}.build" \
		&& mv "${target}.build" "${target}"
