### mk-EA_report ###
# mkfile script with dependency rules for:
#	1. Creating a summarized version of the ExtendAlign results.
#	2. The ouput of this module is intended to be the final pipeline result and the file presented to the user.
#	3. As such, this output should be informative and clear for the user.
#
## For more information about mk dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run recipes
MKSHELL=/bin/bash

## Simplify ExtendAlign results into an output to be presented to the user.
## Parse ExtendAlign table with awk.
%_EA_report.tsv: %.fa.with_nohits.tsv
	## Extract columns of interest, which are: query id, subject id, query length, total mismatch, total match, blastn percent identity, EA percent identity
	Rscript --vanilla format.R $prereq $target
