##
# mkfile script with dependency rules for:
#		1. Creating a summarized version of the Extend Align results
#		2. The ouput of this module is intended to be the final pipeline result and the file presented to the user
#		3. As such, this output should be informative and clear for the user
#
## for more information about mk dependency control, see https://9fans.github.io/plan9port/man/man1/mk.html

## Define shell command line which will be used to run recipes
MKSHELL=/bin/bash

## Simplify EA results into an output to be presented to the user
# parse EA table with a simple awk
%_EA_report.tsv: %.with_nohits.tsv
	## extractcolumns of interest, which are: query id, subject id, query length, total mismatch, total match, blastn percent identity, EA percent identity
	awk '
		###
		# Definition of input and output Field Separator as tab
		BEGIN {OFS=FS="\t"}
		## Replace header
		NR == 1 { print "query_name", "subject_name", "query_length", "EA_total_mismatch", "EA_total_match", "EA_pident", "blastn_pident" }
		## Summarize results
		NR > 1 {
			## Define important columns
				query_name= $2
				subject_name= $4
				query_length= $1
				EA_total_mismatch= $45
				EA_pident= $46
				blastn_pident= $5
			##
			# Restart value
				EA_total_match="ERR"
			# Calculate number of matches using query length minus EA total mismatch
			# TODO (iaguilar) it is posible to precalculate this and print it as a column in the mk-mismatch_recalculation module
				EA_total_match= query_length - EA_total_mismatch
			##
			# Print summarized line
			print query_name, subject_name, query_length, EA_total_mismatch, EA_total_match, EA_pident, blastn_pident
		}
	' $prereq > $target.build \
	&& mv $target.build $target
